# Generated by Django 4.1.5 on 2023-01-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_website',
            new_name='social_github',
        ),
    ]
